src/components/Footer.jsx
src/components/Header.jsx
src/components/Template.jsx
src/shared/App.js
src/shared/GlobalStyles.js

- Template 설정
- 전역 Header component 생성 및 배치
- 전역 Footer component 생성 및 배치
- Global styles 생성 및 적용

2번째 PR : Global Layout 수정 작업

---

src/api/docApi.js
src/components/DocList.jsx
src/components/DocViewer.jsx
src/components/Writer.jsx
src/pages/DocEdit.jsx
src/pages/DocView.jsx
src/redux/modules/document.js
src/shared/Router.js
src/shared/WSRouter.js

- editor 제목 추가
- store와 보여주기, 수정, 삭제 기능 연동
- 서버 통신을 위한 api 생성
- document page 내 history 객체를 통한 이동 추가

PR : document page 서버 연결 전까지 완료

---

package.json
src/api/index.js
src/api/userApi.js
src/pages/Login.jsx
src/redux/modules/user.js
src/shared/cookie.js
yarn.lock

**주요 수정 내용**
-  JWT Access Token 활성화
-  Cookie, Localstorage  에 token과 userInfo 저장
- Redux user module 수정

3번째 PR : pig-backend api server connection (Axios instance 수정 & Login 기능 활성화)

---

src/api/userApi.js
src/components/Header.jsx
src/pages/Login.jsx
src/pages/Register.jsx
src/redux/modules/user.js
src/shared/Router.js
src/shared/auth.js

주요 수정 내용
- auth HOC 적용  (Router component 에서 null, true, false로 접속권한 trigger)
- register api 적용 (회원가입 및 로그인 가능)
- header에 logout 임시 구현

5번째 PR : auth HOC (higher order component) 적용 및 register api 적용

---

src/api/docApi.js
src/components/DocList.jsx
src/components/DocViewer.jsx
src/components/WSTabs.jsx
src/components/Writer.jsx
src/pages/DocAdd.jsx
src/pages/DocEdit.jsx
src/pages/DocView.jsx
src/pages/Workspace.jsx
src/redux/modules/document.js
src/shared/WSRouter.js
src/shared/uploadFile.js

PR : document CRUD 기능 서버 연결 완료

---

src/api/roomApi.js
src/components/AddRoomModal.jsx
src/components/ImgUploader.jsx
src/components/ModifyRoomModal.jsx
src/components/RoomCard.jsx
src/pages/RoomList.jsx
src/redux/modules/image.js
src/redux/modules/room.js

- 파일 선택 전 미리보기를 기본 이미지로 보이도록 수정
- RoomCard와 main페이지 연결

room redux module 서버와 연결

---

src/components/DocList.jsx
src/components/WSTabs.jsx
src/components/Writer.jsx
src/pages/DocBlank.jsx
src/pages/DocView.jsx
src/redux/modules/document.js
src/shared/WSRouter.js

docList가 아직 최신순 정렬이 되지 않아 가장 최근 문서를 보여주는 내용이 적용되지는 않음.
그러나 최신순 정렬을 하면 배열의 0번 인덱스가 가장 최근 문서가 될 예정이므로, 0번 인덱스 문서로 이동하도록 연결
스타일 적용 후 정렬 적용할 예정 - #75

PR - close #28 도큐먼트 페이지 흐름 정리

---

src/api/roomApi.js
src/components/ImgUploader.jsx
src/components/JoinRoomModal.jsx
src/components/RoomCard.jsx
src/redux/modules/room.js

Room exit, join 기능 구현, 서버 연결

---

package.json
src/components/Calendar/CalendarBody.jsx
src/components/Calendar/CalendarHeader.jsx
src/components/WSTabs.jsx
src/pages/Calendar.jsx
src/redux/configStore.js
src/redux/modules/calendar.js
src/shared/WSRouter.js
yarn.lock

- momentjs를 이용한 캘린더 구현
- calendar 모듈 생성
- 매 월 일정을 모두 받아오는 기능 적용

PR : calendar 구현 및 모듈 생성

---

src/feature/board/Bucket.jsx
src/feature/board/Card.jsx
src/feature/board/Chart.jsx
src/feature/board/Todos.jsx
src/redux/modules/board.js
src/redux/modules/todo.js

* bucket, card CRUD 구현 (redux 모듈 + api 연결 사전작업)
* todos module 일부

7th PR : board redux module edit

---

public/index.html
src/elem/Button.jsx
src/elem/Input.jsx
src/elem/Text.jsx
src/pages/Develop.jsx
src/pages/Login.jsx
src/shared/GlobalStyles.js
src/shared/Router.js

* Input
* Text
* Button
* Login page 테스트 적용
> _useHelper, isError를 Props 넣어서 사용하세요._
* 개발 확인용 페이지 추가

8th PR : elem 첫번째 작업, formik 빌드업 

---

src/components/InputToggle.jsx
src/feature/timeline/CalendarHeader.jsx
src/feature/timeline/CalendarInfo.jsx
src/feature/timeline/CalendarModal.jsx
src/feature/timeline/Date.jsx
src/feature/timeline/Dates.jsx
src/pages/Calendar.jsx
src/redux/configStore.js
src/redux/modules/calendar.js
src/redux/modules/date.js

1. calendar.js 를 date.js와 calendar.js로 분리
2. 기 저장된 일정 수정 기능 추가
3. 일정 삭제 기능 추가
4. bug : inputToggle 이용 시 모달이 꺼지는 현상 수정

PR : calendar 수정(기 저장 데이터) 및 삭제 기능 구현 / calendar 모듈 분리

---

src/elem/Button.jsx
src/elem/Input.jsx
src/elem/Text.jsx
src/pages/Login.jsx
src/shared/GlobalStyles.js
src/themes/textStyle.js

- globalStyle 에서 input, textarea, button 기본 스타일 없앰
- textStyle theme 생성 및 적용
- 기존 elem 코드 리팩토링

PR : elem(Input, Button, Text) 스타일 수정 및 textStyle 생성

---

src/components/AccountInfo.jsx
src/components/Header/Header.jsx
src/components/HelpBtns.jsx
src/components/Template.jsx
src/pages/Login.jsx
src/pages/Register.jsx
src/shared/App.js
src/shared/GlobalStyles.js

Login view : close #97 
Register view : close #98

PR : Login, Register 페이지 스타일 적용

---

src/redux/modules/user.js

[Fix PR]  fresh token 서버 업데이트에 대한 대응 코드 수정

[Fix PR]  fresh token 서버 업데이트에 대한 대응 코드 수정

---

src/components/Header/Header.jsx
src/components/WSTabs.jsx
src/feature/document/DocList.jsx
src/feature/document/DocViewer.jsx
src/pages/DocBlank.jsx
src/pages/DocView.jsx
src/pages/Login.jsx
src/pages/Register.jsx
src/pages/Workspace.jsx
src/shared/App.js
src/shared/WSRouter.js
src/themes/responsive.js
src/themes/theme.js

- ThemeProvider 적용 : device, colors(일정, 버킷에 사용할 색상) - close #103 
- Login 모바일 뷰 스타일 - #97 
- Register 모바일 뷰 스타일 - #98 
- Header 모바일 뷰 스타일
- Board Route 연결 - close #104

PR : Header, Login, Register 반응형 적용 및 Workspace 임시 스타일 적용

---

src/components/Header/Header.jsx

- 미로그인 상태에서는 "/"
- 로그인 상태에서는 "/roomlist"

PR : 로그인 상태에서 로고 클릭 시 '/roomlist'로 가도록 변경

---

src/api/roomApi.js
src/components/Drop.jsx
src/feature/room/RoomCard.jsx
src/pages/RoomList.jsx

Dropdown 생성

---

package.json
src/components/WSTabs.jsx
src/feature/document/DocList.jsx
src/feature/document/DocListItem.jsx
src/feature/document/Writer.jsx
src/pages/DocBlank.jsx
src/pages/DocView.jsx
src/pages/Workspace.jsx
src/redux/configStore.js
yarn.lock

- Document List 관련 버그 수정
- 최신 순 정렬 및 기본 문서를 가장 먼저 작성한 문서로 변경 close #75 
- document 탭에서 벗어날 시 initialState로 변경하지 않고 새로 방에 들어가면 document list를 받아오도록 함 - close #74

PR : document 버그 수정 및 redux-devtools-extension 적용

---

src/components/Header/NameTag.jsx
src/components/WSTabs.jsx
src/components/Workspace/WSHeader.jsx
src/components/Workspace/WSTemplate.jsx
src/feature/document/DocList.jsx
src/feature/document/DocViewer.jsx
src/feature/document/Writer.jsx
src/pages/DocBlank.jsx
src/pages/Workspace.jsx
src/shared/GlobalStyles.js

- Header
- 상단에 고정
- 회원 닉네임이 보이게 설정
- tab의 색상 설정
- Document
- 높이 최대치로 지정

PR : Header, Document 스타일 수정

---

src/components/MarkDownEditor.jsx
src/components/MarkDownViewer.jsx
src/elem/IconBtn.jsx
src/elem/Text.jsx
src/elem/Textarea.jsx
src/elem/index.js
src/feature/document/DocViewer.jsx
src/feature/document/Writer.jsx
src/feature/main/Information.jsx
src/feature/main/Members.jsx
src/feature/main/MyTodos.jsx
src/feature/main/Tags.jsx

모두 redux, server 연결 안 한 상태
- #71 - 진행률 그래프 마크업, 스타일 적용
- #72 - 디데이 계산 가능. 마크업, 스타일 적용
- #73 - 할 일 목록 마크업, 스타일 적용. 체크, 삭제 가능

PR : 워크스페이스 메인 페이지 컴포넌트 생성 및 스타일 적용(redux, 서버 연결x)

---

src/api/roomApi.js
src/pages/RoomList.jsx
src/redux/modules/room.js

- onChange로 검색키워드를 감지하여 검색 결과 조회하려고 하였으나
검색키워드 마지막 글자가 잘린 채로 dispatch 됨
- 어쩔 수 없이 enter를 쳐서 결과 조회가 되도록 처리해놓음
- 나중에 onChange만으로 검색결과 조회되도록 수정 필요

searchRoom 기능 추가

---

src/api/roomApi.js
src/feature/room/RoomCard.jsx
src/pages/RoomList.jsx
src/redux/modules/room.js

- 즐겨찾기 했을 때 방이 움직이는 게 사용자에게 좀 더 와닿도록 수정하면 좋겠습니다!
- 추후에 좀 더 좋은 방식으로 변경하고 싶습니다!😆

bookmark 기능 보완

---

src/api/roomApi.js
src/components/Drop.jsx
src/components/ImgUploader.jsx
src/feature/room/JoinRoomModal.jsx
src/feature/room/RoomCard.jsx
src/feature/room/RoomTags.jsx
src/pages/RoomList.jsx
src/redux/modules/room.js

- globalStyles에 수정한 z-index 추가 필요

RoomList 뷰 수정

---

src/api/roomApi.js
src/elem/MemberImg.jsx
src/feature/room/AddRoomModal.jsx
src/feature/room/BookMark.jsx
src/feature/room/JoinRoomModal.jsx
src/feature/room/LinkIcon.jsx
src/feature/room/ModifyRoomModal.jsx
src/feature/room/RoomCard.jsx
src/feature/room/RoomTags.jsx
src/pages/RoomList.jsx
src/redux/modules/room.js

- 검색 기능 보완 필요(즐겨찾기 정보가 표시 안되어 있음)

inviteCode 복사 기능, 검색 기능 수정, JoinModal 완성

---

src/api/roomApi.js
src/components/CountText.jsx
src/components/Header/Header.jsx
src/components/Header/NameTag.jsx
src/components/InputToggle.jsx
src/components/WSTabs.jsx
src/components/Workspace/WSHeader.jsx
src/feature/board/BoardDrop.jsx
src/feature/board/Bucket.jsx
src/feature/board/Card.jsx
src/feature/board/CardModal.jsx
src/feature/board/DatePicker.jsx
src/feature/board/ModalForms.jsx
src/feature/board/Todos.jsx
src/feature/document/Writer.jsx
src/feature/timeline/BucketSelect.jsx
src/feature/timeline/CalendarHeader.jsx
src/feature/timeline/CalendarInfo.jsx
src/feature/timeline/CalendarModalForms.jsx
src/pages/Calendar.jsx
src/pages/DocAdd.jsx
src/pages/Workspace.jsx
src/redux/modules/board.js
src/redux/modules/calendar.js
src/redux/modules/room.js
src/shared/GlobalStyles.js

- Timeline
- Board와 같은 모달 추가
- Board와 같은 api를 이용하여 기능 연결(삭제 미완)
- Bucket 선택 옵션 추가(api 이상으로 추후 변경 예정)
- Board
- 모달 스타일 수정
- 디데이 수정
- 글자 수 제한

PR : Timeline(Calendar) 및 Board 스타일 수정, 남은 기능 연결

---

src/components/Drop.jsx
src/feature/room/RoomCard.jsx

- Drop은 낮에 올려놓았던 커밋이라 같이 들어갔습니다!

RoomCard 뷰 수정, Drop 수정

---

src/feature/room/RoomCard.jsx

즐겨찾기 후 방을 로드해오지 못해서 원래대로 즐겨찾기 수정하였습니다.

즐겨찾기 원래대로 수정

---

src/feature/room/DropDown.jsx
src/feature/room/RoomCard.jsx

- DropDown 안의 수정, 삭제 버튼 클릭 시 수정, 삭제 기능 되고, DropDown도 사라지도록 처리 완료
- 나가기 기능은 갑자기 안됨, 이 부분 월요일에 서버와 얘기하겠습니다!

DropDown 생성 후 수정

---

src/feature/document/DocList.jsx
src/feature/document/DocListItem.jsx
src/feature/document/DocViewer.jsx
src/feature/timeline/BucketSelect.jsx
src/feature/timeline/CalendarInfo.jsx
src/feature/timeline/CalendarModalForms.jsx
src/feature/timeline/Date.jsx
src/pages/Calendar.jsx
src/pages/DocAdd.jsx
src/pages/DocEdit.jsx
src/redux/modules/board.js
src/redux/modules/calendar.js

PR : Timeline 버그 수정 및 확인 모달 생성

---

src/components/ImageModule.jsx
src/pages/Register.jsx
src/shared/uploadFile.js

이미지 모듈을 리팩토링 했습니다.
[방 추가] 부분에서 정해진 규격대로 수정해주시면 됩니다.
자세한 내용은 register 페이지를 참고해주세요.

Instant PR : 이미지 모듈 리팩토링

---

src/api/roomApi.js
src/elem/MemberImg.jsx
src/feature/room/AddRoomModal.jsx
src/feature/room/DropDown.jsx
src/redux/modules/room.js

검색 기능 무한스크롤 : module과 api만 올림, roomList는 수정 중

검색 기능 등 버그 수정

---

src/feature/room/RoomCard.jsx
src/pages/RoomList.jsx

즐겨찾기 이동 버그 수정_RoomList

---

package.json
src/feature/chat/ChatBox.jsx
src/feature/chat/ChatInput.jsx
src/pages/Workspace.jsx
src/shared/useSocket.js
src/themes/hiddenScroll.js
yarn.lock

- 서버와 연결 (connect, disconnect, join, leave, sendMessage, message)
- 서버의 message에 맞춰서 채팅창에 보여주도록 설정
- 채팅창 스크롤을 아래로 맞춤

PR : 채팅 서버와 연결

---

src/api/roomApi.js
src/feature/room/BookmarkList.jsx
src/feature/room/DefaultRoomList.jsx
src/feature/room/RoomCard.jsx
src/feature/room/SearchResult.jsx
src/pages/RoomList.jsx
src/redux/modules/room.js

즐겨찾기 별 깜박임 제거

---

package.json
src/api/index.js
src/feature/chat/Bubble.jsx
src/feature/chat/ChatBox.jsx
src/feature/chat/ChatInput.jsx
src/pages/Workspace.jsx
src/redux/modules/chat.js
src/shared/App.js
src/shared/useSocket.js
yarn.lock

- 채팅 보낸 사람
- 시간
- 프로필 이미지(변경 예정)
- 내가 보낸 메세지와 다른 사람이 보낸 메세지 구분하여 스타일 적용
- 이모지 선택 후 input창이 focus 되도록 설정

PR : 채팅 상세정보 추가 및 스타일 적용

---

src/components/Workspace/WSTemplate.jsx
src/feature/main/myTodos/MyTodos.jsx
src/feature/timeline/Date.jsx
src/pages/DocBlank.jsx
src/pages/Main.jsx

추가로 높이 수정 필요 <- 메인 statusSection 수정 후 변경 예정

PR : 워크스페이스 스타일 수정(캘린더 텍스트 색상, 너비)

---

src/api/index.js
src/api/userApi.js
src/components/Alert.jsx
src/feature/main/Members.jsx
src/pages/Login.jsx
src/pages/Register.jsx
src/redux/configStore.js
src/redux/modules/alert.js
src/redux/modules/user.js
src/shared/Router.js
src/shared/auth.js

* members에서 리덕스 모듈을 변경하지 않아 발생한 방 입장 오류 수정

24th PR : Alert 모달 기능 구현 및 기타 버그 수정

---

src/components/InputToggle.jsx
src/components/WSSidebar.jsx/Notice.jsx
src/components/WSSidebar.jsx/WSSidebar.jsx
src/feature/board/BoardDrop.jsx
src/feature/board/Bucket.jsx
src/feature/board/Card.jsx
src/feature/board/CardModal.jsx
src/feature/board/ModalForms.jsx
src/feature/board/Todo.jsx
src/feature/board/Todos.jsx
src/feature/chat/Chat.jsx
src/feature/chat/ChatInput.jsx
src/feature/document/DocViewer.jsx
src/feature/timeline/BucketSelect.jsx
src/feature/timeline/CalendarHeader.jsx
src/feature/timeline/CalendarModalForms.jsx
src/functions/getModifiedTime.js
src/functions/setDday.js
src/pages/Calendar.jsx

- 버그
- 채팅 빈 칸일 때 제출됨
- 현재로부터 한 달 이상 차이가 나거나 현재시점보다 이전이 마감일인 경우 디데이가 잘못 나타나는 문제
- 문서 마지막 편집 시간이 과도하게 길게 나타남
- 스타일
- 카드 모달 전체 스크롤
- 카드 모달 닫기 버튼 추가
- bucketSelect 위치, 너비
- todo 담당자 드롭다운 
- inputToggle 에서 toggle시마다 텍스트 움직이는 문제
- 사용하지 않는 기능 비활성화

PR : Workspace 내 작은 버그 및 스타일 수정

---

src/api/index.js
src/components/ImageModule.jsx
src/components/MarkDownEditor.jsx
src/components/MarkDownViewer.jsx
src/feature/chat/ChatBox.jsx
src/feature/main/Information.jsx
src/feature/main/myTodos/MyTodos.jsx
src/feature/timeline/BucketSelect.jsx
src/feature/timeline/CalendarInfo.jsx
src/feature/timeline/Dates.jsx
src/feature/timeline/clickDate.js
src/redux/modules/calendar.js
src/redux/modules/date.js
src/redux/modules/document.js
src/redux/modules/room.js
src/redux/modules/user.js
src/themes/toastEditor.css

- 타임라인 모달에서 날짜 변경 시 CalendarInfo에서는 날짜 및 리스트가 변경되지 않는 버그 수정
- 제목 없는 버킷에 '제목 없음' 표시
- 에디터, 뷰어에 폰트 크기 적용
-  높이 설정

PR : workspace 내 버그 수정

---

src/api/index.js
src/components/ImageModule.jsx
src/feature/board/Todos.jsx
src/feature/room/AddRoomModal.jsx
src/pages/Register.jsx
src/shared/useSocket.js

* 이미지 모듈 사진이 재업로드 되지 않는 문제 수정
* 투두를 작성할 때, input을 누르면 내용이 삭제되는 증상 수정

Fix : 이미지모듈 버그 수정, 투두 작성 하는 인풋 수정

---

src/feature/main/Information.jsx
src/feature/main/MemberStatus.jsx
src/feature/main/Members.jsx
src/feature/main/MyStatus.jsx
src/feature/main/ProjectStatus.jsx

- 그래프 색상 수정
- 폰트가 너무 크다는 피드백에 따라 폰트 크기 수정

PR : Workspace - Main 폰트 크기 및 색상 수정

---

src/feature/timeline/CalendarBody.jsx
src/feature/timeline/CalendarHeader.jsx
src/feature/timeline/CalendarInfo.jsx
src/feature/timeline/Date.jsx
src/pages/Calendar.jsx
src/themes/scrollbar.js

PR : Calendar 반응형 스타일 적용

---

src/components/Alert.jsx
src/feature/board/BoardDrop.jsx
src/feature/task/CardModal.jsx
src/feature/timeline/BucketSelect.jsx
src/feature/timeline/CalendarHeader.jsx
src/feature/timeline/CalendarInfo.jsx
src/pages/Calendar.jsx
src/redux/modules/board.js
src/redux/modules/calendar.js
src/redux/modules/error.js

일정, 보드에서의 버킷 수정에 대한 지속적인 테스트가 필요합니다.

Edit : 일정 추가 버튼을 calendarInfo에서 calendarHeader로 변경함

---

src/elem/Textarea.jsx
src/feature/main/InfoDesc.jsx
src/feature/main/InfoHeader.jsx
src/feature/main/InfoSubTitle.jsx
src/feature/main/InfoTags.jsx
src/feature/main/InfoTitle.jsx
src/feature/main/Information.jsx
src/feature/main/MyTodos.jsx
src/feature/main/ProjectStatus.jsx
src/pages/InformationM.jsx
src/pages/MytodosM.jsx
src/pages/StatusM.jsx
src/shared/WSRouter.js

- InformationM, StatusM, MyTodosM 페이지 생성
- Information 여러 컴포넌트로 분리
- InformationM 편집 기능 수정

PR : 모바일 메인 페이지 편집 (Information)

---

src/components/Header/Header.jsx
src/components/Template.jsx
src/components/Workspace/WSHeader.jsx
src/components/Workspace/WSMobileNav.jsx
src/components/Workspace/WSTemplate.jsx
src/feature/chat/Bubble.jsx
src/feature/chat/Chat.jsx
src/feature/chat/ChatBtn.jsx
src/feature/chat/ChatInput.jsx
src/functions/checkDesktop.js
src/pages/ChatM.jsx
src/pages/Workspace.jsx
src/shared/WSRouter.js

모바일, 태블릿 크기 혹은 모바일, 태블릿 환경일 때 채팅이 전체화면이 되도록 설정

PR : 모바일, 태블릿 용 채팅 페이지 생성 및 수정

---

src/components/WSTabs.jsx
src/feature/board/Bucket.jsx
src/feature/task/CardModal.jsx
src/feature/timeline/CalendarHeader.jsx
src/redux/modules/board.js

Feat : 카드 모달 버그 수정 및 기타 불필요한 코드 수정

Feat : 카드 모달 버그 수정 및 기타 불필요한 코드 수정

---

src/components/Confirm.jsx
src/components/InfinityScroll.jsx
src/elem/MemberImg.jsx
src/feature/room/AddRoomModal.jsx
src/feature/room/BookMark.jsx
src/feature/room/BookmarkList.jsx
src/feature/room/DefaultRoomList.jsx
src/feature/room/DropDown.jsx
src/feature/room/JoinRoomModal.jsx
src/feature/room/LinkIcon.jsx
src/feature/room/ModifyRoomModal.jsx
src/feature/room/More.jsx
src/feature/room/RoomBlank.jsx
src/feature/room/RoomCard.jsx
src/feature/room/RoomTags.jsx
src/feature/room/SearchBar.jsx
src/feature/room/SearchResult.jsx
src/redux/modules/room.js

주석을 달아보았습니다...!
그런데 테스트 서버가 계속 닫혀있어서 주석 때문에 에러가 혹시 나는 지는 확인 못했습니다😥

edit : 주석달기

---

src/api/index.js
src/components/Footer.jsx
src/pages/Login.jsx
src/redux/modules/user.js

아이디 저장 기능,, .. 좀 해보려고 했는데.. 아 지금 하기에 좀 늦어서 
그냥 비활성화 할게요.. 괜히 꼬투리 잡혀..

Fix : 회원가입 시 예외처리 되지 않은 API response 처리, 아이디 저장 비활성화... 
